#!/bin/sh

echo "[DotFiles - Submodules Hook]"
echo "  Password is required for private submodules..."

git submodule update --remote

readonly gmod="$(git config --file .gitmodules --get-regexp path | awk '{print $2}')"
echo "  Also updating modules to their latest commit...!"
echo "  Don't forget to check whether or not changes were committed..."
echo "  Modules:"
for m in $gmod; do printf "    ${m} "; git add $m; printf "... done!\n"; done

echo;


